**Task-5&6--> Spam mail Detection**

In [ ]:
import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

In [ ]:
df = pd.read_csv('/content/mail_data (2).csv', encoding='latin-1')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.info()

df.shape

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

Category    0
Message     0
dtype: int64

In [ ]:
df = df[['Category','Message']]
df.columns = ['label','message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r'\d+','',text)

    text = text.translate(
        str.maketrans('','',string.punctuation)
    )

    return text

In [ ]:
df['message'] = df['message'].apply(clean_text)

df.head()

  label                                            message
0   ham  go until jurong point crazy available only in ...
1   ham                            ok lar joking wif u oni
2  spam  free entry in  a wkly comp to win fa cup final...
3   ham        u dun say so early hor u c already then say
4   ham  nah i dont think he goes to usf he lives aroun...

In [ ]:
X = df['message']
y = df['label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)

X_test = vectorizer.transform(X_test)

In [ ]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9560538116591928

In [ ]:
precision = precision_score(
    y_test,
    y_pred,
    pos_label='spam'
)

print("Precision:", precision)

Precision: 1.0

In [ ]:
recall = recall_score(
    y_test,
    y_pred,
    pos_label='spam'
)

print("Recall:", recall)

Recall: 0.6711409395973155

In [ ]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[966   0]
 [ 49 100]]

In [ ]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

         ham       0.95      1.00      0.98       966
        spam       1.00      0.67      0.80       149

    accuracy                           0.96      1115
   macro avg       0.98      0.84      0.89      1115
weighted avg       0.96      0.96      0.95      1115

In [ ]:
email = [
    "Its Emergency,Come and meet me ."
]
email_vector = vectorizer.transform(email)
pred = model.predict(email_vector)

print(pred)
if pred[0] == 'spam':
    print("Spam Mail")
else:
    print("Not Spam Mail")

['ham']
Not Spam Mail